
### To test checkins API, using REST Client plugin in Visual Studio

GET http://localhost:5000/api/checkins

###

GET http://localhost:5000/api/checkins/0

###

POST http://localhost:5000/api/checkins
Content-Type: application/json

{
  "action": "studying",
  "location": "Gerstein",
  "message": "A3 for 369!",
  "userid": "0"
}

###

DELETE http://localhost:5000/api/checkins/5dd989021c9d440000ae3754

### 

PATCH http://localhost:5000/api/users/friends/add/5dd8fe08e57b41fcdd92d492
Content-Type: application/json 

{
  "friendID": "5dd8fc74cfc26ffc10844234"
}

###

PATCH http://localhost:5000/api/users/friends/delete/5dd8fe08e57b41fcdd92d492
Content-Type: application/json 

{
  "friendID": "5dd8fc74cfc26ffc10844234"
}

### 

PATCH http://localhost:5000/api/users/requests/add/5dd8fe08e57b41fcdd92d492
Content-Type: application/json 

{
  "requestFriendID": "5dd8fc74cfc26ffc10844234"
}

###

PATCH http://localhost:5000/api/users/requests/delete/5dd8fe08e57b41fcdd92d492
Content-Type: application/json 

{
  "requestFriendID": "5dd8fc74cfc26ffc10844234"
}

###

GET http://localhost:5000/api/users/all

