
### To test checkins API, using REST Client plugin in Visual Studio

GET http://localhost:5000/api/checkins

###

GET http://localhost:5000/api/checkins/5dd9dc832df28b855ae89edf

###

POST http://localhost:5000/api/checkins
Content-Type: application/json

{
  "action": "eating",
  "location": "Robarts",
  "message": "come join me in the caf!",
  "userid": "5dd8fc74cfc26ffc10844234"
}

###

DELETE http://localhost:5000/api/checkins/5dd989021c9d440000ae3754

### 

PATCH http://localhost:5000/api/users/friends/5dd8fe08e57b41fcdd92d492
Content-Type: application/json 

{
  "friendID": "5dd8fc74cfc26ffc10844234",
  "action": "add"
}

###

PATCH http://localhost:5000/api/users/requests/5dd8fe08e57b41fcdd92d492
Content-Type: application/json 

{
  "requestFriendID": "5dd8fc74cfc26ffc10844234",
  "action": "delete"
}

###

PATCH http://localhost:5000/api/users/requests/delete/5dd8fe08e57b41fcdd92d492
Content-Type: application/json 

{
  "requestFriendID": "5dd8fc74cfc26ffc10844234"
}

###

GET http://localhost:5000/api/users/all

